version: '3.3'
services:
  ### MySQL Container
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - ./.env
  starter:
    image: petapparg/starter
    ports:
      - "8085:8085"
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - mysql
    env_file:
      - ./.env
