version: '3.3'
services:
  ### MySQL Container
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - ./.env
  starter:
    image: petapparg/spring-boot-starter
    ports:
      - "8085:8085"
    depends_on:
      - mysql
